---
# Ansible playbook for shuttting OpenShift Cluster
- name: Shutdown OpenShift Cluster 
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  tasks: 

  - name: Get Nodes
    shell:
      cmd: |
         /usr/local/bin/oc get nodes -o jsonpath={.items[*].metadata.name} > /home/ec2-user/aws_nodes
      warn: False
    ignore_errors: yes

# TEST
